import React from 'react';
import Table from 'react-bootstrap/Table'
import StockService from "../services/StockService";
import {Container} from "react-bootstrap";

import { forwardRef } from 'react';
import Grid from '@material-ui/core/Grid'

import MaterialTable from "material-table";
import AddBox from '@material-ui/icons/AddBox';
import ArrowDownward from '@material-ui/icons/ArrowDownward';
import Check from '@material-ui/icons/Check';
import ChevronLeft from '@material-ui/icons/ChevronLeft';
import ChevronRight from '@material-ui/icons/ChevronRight';
import Clear from '@material-ui/icons/Clear';
import DeleteOutline from '@material-ui/icons/DeleteOutline';
import Edit from '@material-ui/icons/Edit';
import FilterList from '@material-ui/icons/FilterList';
import FirstPage from '@material-ui/icons/FirstPage';
import LastPage from '@material-ui/icons/LastPage';
import Remove from '@material-ui/icons/Remove';
import SaveAlt from '@material-ui/icons/SaveAlt';
import Search from '@material-ui/icons/Search';
import ViewColumn from '@material-ui/icons/ViewColumn';
import axios from 'axios'
import Alert from '@material-ui/lab/Alert';

const tableIcons = {
  Add: forwardRef((props, ref) => <AddBox {...props} ref={ref} />),
  Check: forwardRef((props, ref) => <Check {...props} ref={ref} />),
  Clear: forwardRef((props, ref) => <Clear {...props} ref={ref} />),
  Delete: forwardRef((props, ref) => <DeleteOutline {...props} ref={ref} />),
  DetailPanel: forwardRef((props, ref) => <ChevronRight {...props} ref={ref} />),
  Edit: forwardRef((props, ref) => <Edit {...props} ref={ref} />),
  Export: forwardRef((props, ref) => <SaveAlt {...props} ref={ref} />),
  Filter: forwardRef((props, ref) => <FilterList {...props} ref={ref} />),
  FirstPage: forwardRef((props, ref) => <FirstPage {...props} ref={ref} />),
  LastPage: forwardRef((props, ref) => <LastPage {...props} ref={ref} />),
  NextPage: forwardRef((props, ref) => <ChevronRight {...props} ref={ref} />),
  PreviousPage: forwardRef((props, ref) => <ChevronLeft {...props} ref={ref} />),
  ResetSearch: forwardRef((props, ref) => <Clear {...props} ref={ref} />),
  Search: forwardRef((props, ref) => <Search {...props} ref={ref} />),
  SortArrow: forwardRef((props, ref) => <ArrowDownward {...props} ref={ref} />),
  ThirdStateCheck: forwardRef((props, ref) => <Remove {...props} ref={ref} />),
  ViewColumn: forwardRef((props, ref) => <ViewColumn {...props} ref={ref} />)
};

//https://github.com/effiongcharles/material-ui-table-crud-restapi
class StockComponent extends React.Component {


    constructor(props) {
        super(props);
        this.state = {
            stock: [
                     {
                       "articleId": 361168434,
                       "productId": null,
                       "languageCode": "en",
                       "comment": "",
                       "price": 6.48,
                       "quantity": 1,
                       "inShoppingCart": false,
                       "product": {
                         "productId": 283553,
                         "name": "Hangarback Walker",
                         "categoryId": 1,
                         "categoryName": "Magic Single",
                         "expansionId": null,
                         "metaCardId": null,
                         "dateAdded": null,
                         "metaproductId": null,
                         "totalReprints": null,
                         "localizations": [],
                         "selfUrl": null,
                         "imageUrl": "./img/items/1/ORI/283553.jpg",
                         "game": "MTG",
                         "expansionCollectionNumber": "229",
                         "rarity": "Rare",
                         "expansionName": "Magic Origins",
                         "expansion": null,
                         "priceGuide": null
                       },
                       "seller": null,
                       "lastEdited": [
                         2020,
                         10,
                         27,
                         16,
                         46,
                         36
                       ],
                       "condition": "NEAR_MINT",
                       "foil": false,
                       "signed": false,
                       "altered": false,
                       "playset": false,
                       "firstEdition": false,
                       "articlePriceEntity": {
                         "id": 681,
                         "version": 0,
                         "articleId": 361168434,
                         "recommendedPrice": 6.48,
                         "price": 12
                       }
                     },
                     {
                       "articleId": 361168435,
                       "productId": null,
                       "languageCode": "en",
                       "comment": "",
                       "price": 6.48,
                       "quantity": 1,
                       "inShoppingCart": false,
                       "product": {
                         "productId": 283553,
                         "name": "Hangarback Walker",
                         "categoryId": 1,
                         "categoryName": "Magic Single",
                         "expansionId": null,
                         "metaCardId": null,
                         "dateAdded": null,
                         "metaproductId": null,
                         "totalReprints": null,
                         "localizations": [],
                         "selfUrl": null,
                         "imageUrl": "./img/items/1/ORI/283553.jpg",
                         "game": "MTG",
                         "expansionCollectionNumber": "229",
                         "rarity": "Rare",
                         "expansionName": "Magic Origins",
                         "expansion": null,
                         "priceGuide": null
                       },
                       "seller": null,
                       "lastEdited": [
                         2020,
                         10,
                         27,
                         16,
                         46,
                         36
                       ],
                       "condition": "NEAR_MINT",
                       "foil": false,
                       "signed": false,
                       "altered": false,
                       "playset": false,
                       "firstEdition": false,
                       "articlePriceEntity": {
                         "id": 682,
                         "version": 0,
                         "articleId": 361168435,
                         "recommendedPrice": 6.48,
                         "price": 13
                       }
                     },
                     {
                       "articleId": 361168440,
                       "productId": null,
                       "languageCode": "en",
                       "comment": "",
                       "price": 6.48,
                       "quantity": 1,
                       "inShoppingCart": false,
                       "product": {
                         "productId": 283553,
                         "name": "Hangarback Walker",
                         "categoryId": 1,
                         "categoryName": "Magic Single",
                         "expansionId": null,
                         "metaCardId": null,
                         "dateAdded": null,
                         "metaproductId": null,
                         "totalReprints": null,
                         "localizations": [],
                         "selfUrl": null,
                         "imageUrl": "./img/items/1/ORI/283553.jpg",
                         "game": "MTG",
                         "expansionCollectionNumber": "229",
                         "rarity": "Rare",
                         "expansionName": "Magic Origins",
                         "expansion": null,
                         "priceGuide": null
                       },
                       "seller": null,
                       "lastEdited": [
                         2020,
                         10,
                         27,
                         16,
                         46,
                         36
                       ],
                       "condition": "NEAR_MINT",
                       "foil": false,
                       "signed": false,
                       "altered": false,
                       "playset": false,
                       "firstEdition": false,
                       "articlePriceEntity": {
                         "id": 691,
                         "version": 0,
                         "articleId": 361168440,
                         "recommendedPrice": 6.48,
                         "price": 16
                       }
                     },
                     {
                       "articleId": 361168439,
                       "productId": null,
                       "languageCode": "en",
                       "comment": "",
                       "price": 18,
                       "quantity": 1,
                       "inShoppingCart": false,
                       "product": {
                         "productId": 283553,
                         "name": "Hangarback Walker",
                         "categoryId": 1,
                         "categoryName": "Magic Single",
                         "expansionId": null,
                         "metaCardId": null,
                         "dateAdded": null,
                         "metaproductId": null,
                         "totalReprints": null,
                         "localizations": [],
                         "selfUrl": null,
                         "imageUrl": "./img/items/1/ORI/283553.jpg",
                         "game": "MTG",
                         "expansionCollectionNumber": "229",
                         "rarity": "Rare",
                         "expansionName": "Magic Origins",
                         "expansion": null,
                         "priceGuide": null
                       },
                       "seller": null,
                       "lastEdited": [
                         2020,
                         10,
                         27,
                         16,
                         46,
                         36
                       ],
                       "condition": "GOOD",
                       "foil": false,
                       "signed": false,
                       "altered": false,
                       "playset": false,
                       "firstEdition": false,
                       "articlePriceEntity": {
                         "id": 679,
                         "version": 0,
                         "articleId": 361168439,
                         "recommendedPrice": 18,
                         "price": 18
                       }
                     },
                     {
                       "articleId": 361168444,
                       "productId": null,
                       "languageCode": "en",
                       "comment": "",
                       "price": 6.48,
                       "quantity": 1,
                       "inShoppingCart": false,
                       "product": {
                         "productId": 283553,
                         "name": "Hangarback Walker",
                         "categoryId": 1,
                         "categoryName": "Magic Single",
                         "expansionId": null,
                         "metaCardId": null,
                         "dateAdded": null,
                         "metaproductId": null,
                         "totalReprints": null,
                         "localizations": [],
                         "selfUrl": null,
                         "imageUrl": "./img/items/1/ORI/283553.jpg",
                         "game": "MTG",
                         "expansionCollectionNumber": "229",
                         "rarity": "Rare",
                         "expansionName": "Magic Origins",
                         "expansion": null,
                         "priceGuide": null
                       },
                       "seller": null,
                       "lastEdited": [
                         2020,
                         10,
                         27,
                         16,
                         46,
                         36
                       ],
                       "condition": "NEAR_MINT",
                       "foil": false,
                       "signed": false,
                       "altered": false,
                       "playset": false,
                       "firstEdition": false,
                       "articlePriceEntity": {
                         "id": 687,
                         "version": 0,
                         "articleId": 361168444,
                         "recommendedPrice": 6.48,
                         "price": 45
                       }
                     },
                     {
                       "articleId": 361168442,
                       "productId": null,
                       "languageCode": "en",
                       "comment": "",
                       "price": 6.48,
                       "quantity": 1,
                       "inShoppingCart": false,
                       "product": {
                         "productId": 283553,
                         "name": "Hangarback Walker",
                         "categoryId": 1,
                         "categoryName": "Magic Single",
                         "expansionId": null,
                         "metaCardId": null,
                         "dateAdded": null,
                         "metaproductId": null,
                         "totalReprints": null,
                         "localizations": [],
                         "selfUrl": null,
                         "imageUrl": "./img/items/1/ORI/283553.jpg",
                         "game": "MTG",
                         "expansionCollectionNumber": "229",
                         "rarity": "Rare",
                         "expansionName": "Magic Origins",
                         "expansion": null,
                         "priceGuide": null
                       },
                       "seller": null,
                       "lastEdited": [
                         2020,
                         10,
                         27,
                         16,
                         46,
                         36
                       ],
                       "condition": "NEAR_MINT",
                       "foil": false,
                       "signed": false,
                       "altered": false,
                       "playset": false,
                       "firstEdition": false,
                       "articlePriceEntity": {
                         "id": 689,
                         "version": 0,
                         "articleId": 361168442,
                         "recommendedPrice": 6.48,
                         "price": 52
                       }
                     },
                     {
                       "articleId": 361168441,
                       "productId": null,
                       "languageCode": "en",
                       "comment": "",
                       "price": 6.48,
                       "quantity": 1,
                       "inShoppingCart": false,
                       "product": {
                         "productId": 283553,
                         "name": "Hangarback Walker",
                         "categoryId": 1,
                         "categoryName": "Magic Single",
                         "expansionId": null,
                         "metaCardId": null,
                         "dateAdded": null,
                         "metaproductId": null,
                         "totalReprints": null,
                         "localizations": [],
                         "selfUrl": null,
                         "imageUrl": "./img/items/1/ORI/283553.jpg",
                         "game": "MTG",
                         "expansionCollectionNumber": "229",
                         "rarity": "Rare",
                         "expansionName": "Magic Origins",
                         "expansion": null,
                         "priceGuide": null
                       },
                       "seller": null,
                       "lastEdited": [
                         2020,
                         10,
                         27,
                         16,
                         46,
                         36
                       ],
                       "condition": "NEAR_MINT",
                       "foil": false,
                       "signed": false,
                       "altered": false,
                       "playset": false,
                       "firstEdition": false,
                       "articlePriceEntity": {
                         "id": 692,
                         "version": 0,
                         "articleId": 361168441,
                         "recommendedPrice": 6.48,
                         "price": 99
                       }
                     },
                     {
                       "articleId": 361168432,
                       "productId": null,
                       "languageCode": "en",
                       "comment": "",
                       "price": 6.48,
                       "quantity": 2,
                       "inShoppingCart": false,
                       "product": {
                         "productId": 283553,
                         "name": "Hangarback Walker",
                         "categoryId": 1,
                         "categoryName": "Magic Single",
                         "expansionId": null,
                         "metaCardId": null,
                         "dateAdded": null,
                         "metaproductId": null,
                         "totalReprints": null,
                         "localizations": [],
                         "selfUrl": null,
                         "imageUrl": "./img/items/1/ORI/283553.jpg",
                         "game": "MTG",
                         "expansionCollectionNumber": "229",
                         "rarity": "Rare",
                         "expansionName": "Magic Origins",
                         "expansion": null,
                         "priceGuide": null
                       },
                       "seller": null,
                       "lastEdited": [
                         2020,
                         10,
                         27,
                         16,
                         51,
                         52
                       ],
                       "condition": "NEAR_MINT",
                       "foil": false,
                       "signed": false,
                       "altered": false,
                       "playset": false,
                       "firstEdition": false,
                       "articlePriceEntity": {
                         "id": 683,
                         "version": 0,
                         "articleId": 361168432,
                         "recommendedPrice": 6.48,
                         "price": 100
                       }
                     },
                     {
                       "articleId": 361168438,
                       "productId": null,
                       "languageCode": "en",
                       "comment": "",
                       "price": 6.48,
                       "quantity": 1,
                       "inShoppingCart": false,
                       "product": {
                         "productId": 283553,
                         "name": "Hangarback Walker",
                         "categoryId": 1,
                         "categoryName": "Magic Single",
                         "expansionId": null,
                         "metaCardId": null,
                         "dateAdded": null,
                         "metaproductId": null,
                         "totalReprints": null,
                         "localizations": [],
                         "selfUrl": null,
                         "imageUrl": "./img/items/1/ORI/283553.jpg",
                         "game": "MTG",
                         "expansionCollectionNumber": "229",
                         "rarity": "Rare",
                         "expansionName": "Magic Origins",
                         "expansion": null,
                         "priceGuide": null
                       },
                       "seller": null,
                       "lastEdited": [
                         2020,
                         10,
                         27,
                         16,
                         46,
                         36
                       ],
                       "condition": "NEAR_MINT",
                       "foil": false,
                       "signed": false,
                       "altered": false,
                       "playset": false,
                       "firstEdition": false,
                       "articlePriceEntity": {
                         "id": 678,
                         "version": 0,
                         "articleId": 361168438,
                         "recommendedPrice": 6.48,
                         "price": 136
                       }
                     },
                     {
                       "articleId": 361168436,
                       "productId": null,
                       "languageCode": "en",
                       "comment": "",
                       "price": 6.48,
                       "quantity": 1,
                       "inShoppingCart": false,
                       "product": {
                         "productId": 283553,
                         "name": "Hangarback Walker",
                         "categoryId": 1,
                         "categoryName": "Magic Single",
                         "expansionId": null,
                         "metaCardId": null,
                         "dateAdded": null,
                         "metaproductId": null,
                         "totalReprints": null,
                         "localizations": [],
                         "selfUrl": null,
                         "imageUrl": "./img/items/1/ORI/283553.jpg",
                         "game": "MTG",
                         "expansionCollectionNumber": "229",
                         "rarity": "Rare",
                         "expansionName": "Magic Origins",
                         "expansion": null,
                         "priceGuide": null
                       },
                       "seller": null,
                       "lastEdited": [
                         2020,
                         10,
                         27,
                         16,
                         46,
                         36
                       ],
                       "condition": "NEAR_MINT",
                       "foil": false,
                       "signed": false,
                       "altered": false,
                       "playset": false,
                       "firstEdition": false,
                       "articlePriceEntity": {
                         "id": 680,
                         "version": 0,
                         "articleId": 361168436,
                         "recommendedPrice": 6.48,
                         "price": 144
                       }
                     },
                     {
                       "articleId": 361168443,
                       "productId": null,
                       "languageCode": "en",
                       "comment": "",
                       "price": 6.48,
                       "quantity": 1,
                       "inShoppingCart": false,
                       "product": {
                         "productId": 283553,
                         "name": "Hangarback Walker",
                         "categoryId": 1,
                         "categoryName": "Magic Single",
                         "expansionId": null,
                         "metaCardId": null,
                         "dateAdded": null,
                         "metaproductId": null,
                         "totalReprints": null,
                         "localizations": [],
                         "selfUrl": null,
                         "imageUrl": "./img/items/1/ORI/283553.jpg",
                         "game": "MTG",
                         "expansionCollectionNumber": "229",
                         "rarity": "Rare",
                         "expansionName": "Magic Origins",
                         "expansion": null,
                         "priceGuide": null
                       },
                       "seller": null,
                       "lastEdited": [
                         2020,
                         10,
                         27,
                         16,
                         46,
                         36
                       ],
                       "condition": "NEAR_MINT",
                       "foil": false,
                       "signed": false,
                       "altered": false,
                       "playset": false,
                       "firstEdition": false,
                       "articlePriceEntity": {
                         "id": 690,
                         "version": 0,
                         "articleId": 361168443,
                         "recommendedPrice": 6.48,
                         "price": 951
                       }
                     },
                     {
                       "articleId": 361182840,
                       "productId": null,
                       "languageCode": "en",
                       "comment": "abcdef",
                       "price": 12.24,
                       "quantity": 1,
                       "inShoppingCart": false,
                       "product": {
                         "productId": 301211,
                         "name": "Vraska's Contempt",
                         "categoryId": 1,
                         "categoryName": "Magic Single",
                         "expansionId": null,
                         "metaCardId": null,
                         "dateAdded": null,
                         "metaproductId": null,
                         "totalReprints": null,
                         "localizations": [],
                         "selfUrl": null,
                         "imageUrl": "./img/items/1/XLN/301211.jpg",
                         "game": "MTG",
                         "expansionCollectionNumber": "129",
                         "rarity": "Rare",
                         "expansionName": "Ixalan",
                         "expansion": null,
                         "priceGuide": null
                       },
                       "seller": null,
                       "lastEdited": [
                         2020,
                         10,
                         27,
                         21,
                         25,
                         35
                       ],
                       "condition": "EXCELLENT",
                       "foil": false,
                       "signed": false,
                       "altered": false,
                       "playset": false,
                       "firstEdition": false,
                       "articlePriceEntity": {
                         "id": 700,
                         "version": 0,
                         "articleId": 361182840,
                         "recommendedPrice": 12.24,
                         "price": 12.95
                       }
                     },
                     {
                       "articleId": 361168426,
                       "productId": null,
                       "languageCode": "en",
                       "comment": "",
                       "price": 16.88,
                       "quantity": 1,
                       "inShoppingCart": false,
                       "product": {
                         "productId": 301546,
                         "name": "Search for Azcanta / Azcanta, the Sunken Ruin",
                         "categoryId": 1,
                         "categoryName": "Magic Single",
                         "expansionId": null,
                         "metaCardId": null,
                         "dateAdded": null,
                         "metaproductId": null,
                         "totalReprints": null,
                         "localizations": [],
                         "selfUrl": null,
                         "imageUrl": "./img/items/1/XLN/301546.jpg",
                         "game": "MTG",
                         "expansionCollectionNumber": "74",
                         "rarity": "Rare",
                         "expansionName": "Ixalan",
                         "expansion": null,
                         "priceGuide": null
                       },
                       "seller": null,
                       "lastEdited": [
                         2020,
                         10,
                         27,
                         16,
                         51,
                         52
                       ],
                       "condition": "NEAR_MINT",
                       "foil": false,
                       "signed": false,
                       "altered": false,
                       "playset": false,
                       "firstEdition": false,
                       "articlePriceEntity": {
                         "id": 676,
                         "version": 0,
                         "articleId": 361168426,
                         "recommendedPrice": 16.88,
                         "price": 500
                       }
                     },
                     {
                       "articleId": 361168451,
                       "productId": null,
                       "languageCode": "en",
                       "comment": "tsdfsd",
                       "price": 1,
                       "quantity": 1,
                       "inShoppingCart": false,
                       "product": {
                         "productId": 301721,
                         "name": "Field of Ruin",
                         "categoryId": 1,
                         "categoryName": "Magic Single",
                         "expansionId": null,
                         "metaCardId": null,
                         "dateAdded": null,
                         "metaproductId": null,
                         "totalReprints": null,
                         "localizations": [],
                         "selfUrl": null,
                         "imageUrl": "./img/items/1/XLN/301721.jpg",
                         "game": "MTG",
                         "expansionCollectionNumber": "254",
                         "rarity": "Uncommon",
                         "expansionName": "Ixalan",
                         "expansion": null,
                         "priceGuide": null
                       },
                       "seller": null,
                       "lastEdited": [
                         2020,
                         10,
                         27,
                         15,
                         52
                       ],
                       "condition": "NEAR_MINT",
                       "foil": false,
                       "signed": false,
                       "altered": false,
                       "playset": false,
                       "firstEdition": false,
                       "articlePriceEntity": {
                         "id": 696,
                         "version": 0,
                         "articleId": 361168451,
                         "recommendedPrice": 1,
                         "price": 1
                       }
                     },
                     {
                       "articleId": 361168450,
                       "productId": null,
                       "languageCode": "en",
                       "comment": "dsf",
                       "price": 1,
                       "quantity": 1,
                       "inShoppingCart": false,
                       "product": {
                         "productId": 301721,
                         "name": "Field of Ruin",
                         "categoryId": 1,
                         "categoryName": "Magic Single",
                         "expansionId": null,
                         "metaCardId": null,
                         "dateAdded": null,
                         "metaproductId": null,
                         "totalReprints": null,
                         "localizations": [],
                         "selfUrl": null,
                         "imageUrl": "./img/items/1/XLN/301721.jpg",
                         "game": "MTG",
                         "expansionCollectionNumber": "254",
                         "rarity": "Uncommon",
                         "expansionName": "Ixalan",
                         "expansion": null,
                         "priceGuide": null
                       },
                       "seller": null,
                       "lastEdited": [
                         2020,
                         10,
                         27,
                         15,
                         52,
                         6
                       ],
                       "condition": "NEAR_MINT",
                       "foil": false,
                       "signed": false,
                       "altered": false,
                       "playset": false,
                       "firstEdition": false,
                       "articlePriceEntity": {
                         "id": 695,
                         "version": 0,
                         "articleId": 361168450,
                         "recommendedPrice": 1,
                         "price": 2
                       }
                     },
                     {
                       "articleId": 361168448,
                       "productId": null,
                       "languageCode": "en",
                       "comment": "",
                       "price": 1,
                       "quantity": 2,
                       "inShoppingCart": false,
                       "product": {
                         "productId": 301721,
                         "name": "Field of Ruin",
                         "categoryId": 1,
                         "categoryName": "Magic Single",
                         "expansionId": null,
                         "metaCardId": null,
                         "dateAdded": null,
                         "metaproductId": null,
                         "totalReprints": null,
                         "localizations": [],
                         "selfUrl": null,
                         "imageUrl": "./img/items/1/XLN/301721.jpg",
                         "game": "MTG",
                         "expansionCollectionNumber": "254",
                         "rarity": "Uncommon",
                         "expansionName": "Ixalan",
                         "expansion": null,
                         "priceGuide": null
                       },
                       "seller": null,
                       "lastEdited": [
                         2020,
                         10,
                         27,
                         16,
                         46,
                         36
                       ],
                       "condition": "NEAR_MINT",
                       "foil": false,
                       "signed": false,
                       "altered": false,
                       "playset": false,
                       "firstEdition": false,
                       "articlePriceEntity": {
                         "id": 697,
                         "version": 0,
                         "articleId": 361168448,
                         "recommendedPrice": 1,
                         "price": 3
                       }
                     },
                     {
                       "articleId": 361168452,
                       "productId": null,
                       "languageCode": "en",
                       "comment": "",
                       "price": 1,
                       "quantity": 12,
                       "inShoppingCart": false,
                       "product": {
                         "productId": 301721,
                         "name": "Field of Ruin",
                         "categoryId": 1,
                         "categoryName": "Magic Single",
                         "expansionId": null,
                         "metaCardId": null,
                         "dateAdded": null,
                         "metaproductId": null,
                         "totalReprints": null,
                         "localizations": [],
                         "selfUrl": null,
                         "imageUrl": "./img/items/1/XLN/301721.jpg",
                         "game": "MTG",
                         "expansionCollectionNumber": "254",
                         "rarity": "Uncommon",
                         "expansionName": "Ixalan",
                         "expansion": null,
                         "priceGuide": null
                       },
                       "seller": null,
                       "lastEdited": [
                         2020,
                         10,
                         27,
                         16,
                         46,
                         36
                       ],
                       "condition": "NEAR_MINT",
                       "foil": false,
                       "signed": false,
                       "altered": false,
                       "playset": false,
                       "firstEdition": false,
                       "articlePriceEntity": {
                         "id": 693,
                         "version": 0,
                         "articleId": 361168452,
                         "recommendedPrice": 1,
                         "price": 4
                       }
                     },
                     {
                       "articleId": 361168447,
                       "productId": null,
                       "languageCode": "en",
                       "comment": "",
                       "price": 1,
                       "quantity": 4,
                       "inShoppingCart": false,
                       "product": {
                         "productId": 301721,
                         "name": "Field of Ruin",
                         "categoryId": 1,
                         "categoryName": "Magic Single",
                         "expansionId": null,
                         "metaCardId": null,
                         "dateAdded": null,
                         "metaproductId": null,
                         "totalReprints": null,
                         "localizations": [],
                         "selfUrl": null,
                         "imageUrl": "./img/items/1/XLN/301721.jpg",
                         "game": "MTG",
                         "expansionCollectionNumber": "254",
                         "rarity": "Uncommon",
                         "expansionName": "Ixalan",
                         "expansion": null,
                         "priceGuide": null
                       },
                       "seller": null,
                       "lastEdited": [
                         2020,
                         10,
                         27,
                         16,
                         46,
                         36
                       ],
                       "condition": "NEAR_MINT",
                       "foil": false,
                       "signed": false,
                       "altered": false,
                       "playset": false,
                       "firstEdition": false,
                       "articlePriceEntity": {
                         "id": 686,
                         "version": 0,
                         "articleId": 361168447,
                         "recommendedPrice": 1,
                         "price": 5
                       }
                     },
                     {
                       "articleId": 361168449,
                       "productId": null,
                       "languageCode": "en",
                       "comment": "",
                       "price": 1,
                       "quantity": 2,
                       "inShoppingCart": false,
                       "product": {
                         "productId": 301721,
                         "name": "Field of Ruin",
                         "categoryId": 1,
                         "categoryName": "Magic Single",
                         "expansionId": null,
                         "metaCardId": null,
                         "dateAdded": null,
                         "metaproductId": null,
                         "totalReprints": null,
                         "localizations": [],
                         "selfUrl": null,
                         "imageUrl": "./img/items/1/XLN/301721.jpg",
                         "game": "MTG",
                         "expansionCollectionNumber": "254",
                         "rarity": "Uncommon",
                         "expansionName": "Ixalan",
                         "expansion": null,
                         "priceGuide": null
                       },
                       "seller": null,
                       "lastEdited": [
                         2020,
                         10,
                         27,
                         16,
                         46,
                         36
                       ],
                       "condition": "NEAR_MINT",
                       "foil": false,
                       "signed": false,
                       "altered": false,
                       "playset": false,
                       "firstEdition": false,
                       "articlePriceEntity": {
                         "id": 698,
                         "version": 0,
                         "articleId": 361168449,
                         "recommendedPrice": 1,
                         "price": 7
                       }
                     },
                     {
                       "articleId": 361168446,
                       "productId": null,
                       "languageCode": "en",
                       "comment": "",
                       "price": 1,
                       "quantity": 4,
                       "inShoppingCart": false,
                       "product": {
                         "productId": 301721,
                         "name": "Field of Ruin",
                         "categoryId": 1,
                         "categoryName": "Magic Single",
                         "expansionId": null,
                         "metaCardId": null,
                         "dateAdded": null,
                         "metaproductId": null,
                         "totalReprints": null,
                         "localizations": [],
                         "selfUrl": null,
                         "imageUrl": "./img/items/1/XLN/301721.jpg",
                         "game": "MTG",
                         "expansionCollectionNumber": "254",
                         "rarity": "Uncommon",
                         "expansionName": "Ixalan",
                         "expansion": null,
                         "priceGuide": null
                       },
                       "seller": null,
                       "lastEdited": [
                         2020,
                         10,
                         27,
                         16,
                         46,
                         36
                       ],
                       "condition": "NEAR_MINT",
                       "foil": false,
                       "signed": false,
                       "altered": false,
                       "playset": false,
                       "firstEdition": false,
                       "articlePriceEntity": {
                         "id": 685,
                         "version": 0,
                         "articleId": 361168446,
                         "recommendedPrice": 1,
                         "price": 8
                       }
                     },
                     {
                       "articleId": 361168445,
                       "productId": null,
                       "languageCode": "en",
                       "comment": "",
                       "price": 1,
                       "quantity": 3,
                       "inShoppingCart": false,
                       "product": {
                         "productId": 301721,
                         "name": "Field of Ruin",
                         "categoryId": 1,
                         "categoryName": "Magic Single",
                         "expansionId": null,
                         "metaCardId": null,
                         "dateAdded": null,
                         "metaproductId": null,
                         "totalReprints": null,
                         "localizations": [],
                         "selfUrl": null,
                         "imageUrl": "./img/items/1/XLN/301721.jpg",
                         "game": "MTG",
                         "expansionCollectionNumber": "254",
                         "rarity": "Uncommon",
                         "expansionName": "Ixalan",
                         "expansion": null,
                         "priceGuide": null
                       },
                       "seller": null,
                       "lastEdited": [
                         2020,
                         10,
                         27,
                         16,
                         46,
                         36
                       ],
                       "condition": "NEAR_MINT",
                       "foil": false,
                       "signed": false,
                       "altered": false,
                       "playset": false,
                       "firstEdition": false,
                       "articlePriceEntity": {
                         "id": 688,
                         "version": 0,
                         "articleId": 361168445,
                         "recommendedPrice": 1,
                         "price": 9
                       }
                     },
                     {
                       "articleId": 361168453,
                       "productId": null,
                       "languageCode": "en",
                       "comment": "",
                       "price": 1,
                       "quantity": 2,
                       "inShoppingCart": false,
                       "product": {
                         "productId": 301721,
                         "name": "Field of Ruin",
                         "categoryId": 1,
                         "categoryName": "Magic Single",
                         "expansionId": null,
                         "metaCardId": null,
                         "dateAdded": null,
                         "metaproductId": null,
                         "totalReprints": null,
                         "localizations": [],
                         "selfUrl": null,
                         "imageUrl": "./img/items/1/XLN/301721.jpg",
                         "game": "MTG",
                         "expansionCollectionNumber": "254",
                         "rarity": "Uncommon",
                         "expansionName": "Ixalan",
                         "expansion": null,
                         "priceGuide": null
                       },
                       "seller": null,
                       "lastEdited": [
                         2020,
                         10,
                         27,
                         16,
                         46,
                         36
                       ],
                       "condition": "NEAR_MINT",
                       "foil": false,
                       "signed": false,
                       "altered": false,
                       "playset": false,
                       "firstEdition": false,
                       "articlePriceEntity": {
                         "id": 694,
                         "version": 0,
                         "articleId": 361168453,
                         "recommendedPrice": 1,
                         "price": 44
                       }
                     },
                     {
                       "articleId": 361168425,
                       "productId": null,
                       "languageCode": "en",
                       "comment": "",
                       "price": 3.49,
                       "quantity": 1,
                       "inShoppingCart": false,
                       "product": {
                         "productId": 301721,
                         "name": "Field of Ruin",
                         "categoryId": 1,
                         "categoryName": "Magic Single",
                         "expansionId": null,
                         "metaCardId": null,
                         "dateAdded": null,
                         "metaproductId": null,
                         "totalReprints": null,
                         "localizations": [],
                         "selfUrl": null,
                         "imageUrl": "./img/items/1/XLN/301721.jpg",
                         "game": "MTG",
                         "expansionCollectionNumber": "254",
                         "rarity": "Uncommon",
                         "expansionName": "Ixalan",
                         "expansion": null,
                         "priceGuide": null
                       },
                       "seller": null,
                       "lastEdited": [
                         2020,
                         10,
                         29,
                         18,
                         48,
                         1
                       ],
                       "condition": "EXCELLENT",
                       "foil": false,
                       "signed": false,
                       "altered": false,
                       "playset": false,
                       "firstEdition": false,
                       "articlePriceEntity": {
                         "id": 677,
                         "version": 0,
                         "articleId": 361168425,
                         "recommendedPrice": 3.49,
                         "price": 1003.4
                       }
                     },
                     {
                       "articleId": 361168433,
                       "productId": null,
                       "languageCode": "en",
                       "comment": "1",
                       "price": 6.48,
                       "quantity": 1,
                       "inShoppingCart": false,
                       "product": {
                         "productId": 283553,
                         "name": "Hangarback Walker",
                         "categoryId": 1,
                         "categoryName": "Magic Single",
                         "expansionId": null,
                         "metaCardId": null,
                         "dateAdded": null,
                         "metaproductId": null,
                         "totalReprints": null,
                         "localizations": [],
                         "selfUrl": null,
                         "imageUrl": "./img/items/1/ORI/283553.jpg",
                         "game": "MTG",
                         "expansionCollectionNumber": "229",
                         "rarity": "Rare",
                         "expansionName": "Magic Origins",
                         "expansion": null,
                         "priceGuide": null
                       },
                       "seller": null,
                       "lastEdited": [
                         2020,
                         11,
                         5,
                         8,
                         51,
                         38
                       ],
                       "condition": "NEAR_MINT",
                       "foil": false,
                       "signed": false,
                       "altered": false,
                       "playset": false,
                       "firstEdition": false,
                       "articlePriceEntity": {
                         "id": 684,
                         "version": 0,
                         "articleId": 361168433,
                         "recommendedPrice": 6.48,
                         "price": 117.2
                       }
                     }
                   ],
            columns: [
                      {title: "id", field: "articleId", hidden: true},
                      {title: "articleId", field: "articleId"},
                      {title: "recommendedPrice", field: "price"},
                      {title: "currentPrice", field: "articlePriceEntity.price"},
                      {title: "comment", field: "comment"},
                      {title: "quantity", field: "quantity"},
                      {title: "condition", field: "condition"},
                      {title: "p.name", field: "product.name"},
                      {title: "p.expansionName", field: "product.expansionName"},
                      {title: "languageCode", field: "languageCode"},
                      {title: "foil", field: "foil"},
                      {title: "signed", field: "signed"},
                      {title: "altered", field: "altered"},
                      {title: "playset", field: "playset"},
                      {title: "p.imageUrl", field: "product.imageUrl"},
                      {title: "p.game", field: "product.game"},
                      {title: "p.expansionCollectionNumber", field: "product.expansionCollectionNumber"},
                      {title: "p.rarity", field: "product.rarity"},
                      {title: "productId", field: "productId"},
                      ],
                      title: "My Stock",
      }
    }



    componentDidMount() {
        StockService.getStockInformation().then((response) => {
            console.log(response.data)
            this.setState({stock: response.data})
        });
    }

    render() {
        return (
        <MaterialTable
         title={this.state.title}
         columns={this.state.columns}
                     data={this.state.stock}
                     icons={tableIcons}
        />
        )
    }
}

export default StockComponent